server {
    # Listen on port 80 and serve the nginx html directory
    listen 80;
    server_name localhost;
    # Serve the nginx html directory to make the files accessible to the browser
    root /usr/share/nginx/html;
    index index.html;

    # Serve the index.html file for all requests
    location / {
        try_files $uri $uri/ /index.html;
    }
}