spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/inventory
    username: inventory
    password: inventory
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/inventory}
          jwk-set-uri: http://localhost:8081/realms/inventory/protocol/openid-connect/certs

app:
  keycloak:
    client-id: ${KEYCLOAK_CLIENT_ID:inventory-api}